### PR TITLE
Clear recommended results on popupclose (closes #82).

### LINKED ISSUE #82: We should clear Little Machine results as soon as they're no longer congruent with the search terms
As demonstrated [in this video](http://chuck.mn/1w3q3r011b0W), Little Machine results are not immediately cleared when they no longer match the search terms; instead, they wait for updated results from the service. Screencap from the ~100ms where it's wrong

screen shot 2015-11-23 at 1 27 24 pm

It's a little subtle, but it feels pretty bad.

### PR DESCRIPTION
**Pull request by chuckharmston**
@6a68, everything I know about WebChannel says this should work, but I'm not seeing the callback run when the event is fired. Any chance I'm missing something?

### CODE REVIEW

**Comment by jaredhirsch** [comment]
@chuckharmston I think the problem is that [this line](https://github.com/mozilla/universal-search-content/blob/master/src/lib/web_channel.js#L47) only publishes messages if `message.data` is truthy, but popupclose [has a `null` data field](https://github.com/mozilla/universal-search-addon/blob/master/docs/API.md#popupclose).

That check probably should be updated to make sure `message.type` exists, since we don't want to be routing an `undefined` message type, but not worry about `message.data`.

**Comment by jaredhirsch** [comment]
Note also that if the popup is pinned, the popupclose event won't be sent.

One relatively clean way to test this is to open the browser toolbox, trigger a delayed popupclose event in the console:

```
setTimeout(() => { window.US.transport.onPopupClose() }, 10 * 1000);
```

That gives you 10 seconds to toggle over to the iframe and allow the debugger to attach to any breakpoints you've set on the iframe side:

**Comment by chuckharmston** [comment]
That was exactly it, thanks for the lead @6a68. Slightly embarrassing miss on my part.

**Comment by chuckharmston** [comment]
This is a big UX win, it feels a lot better.

**Pull request merged**
